version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: aws-cdk
    versions:
    - 1.98.0
- package-ecosystem: pip
  directory: "/assets/simple-id-app"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
